import { Category, CustomOrder, Drop, Product } from "./types";

// Placeholder images from Unsplash — substituir por fotos reais da marca
const img = (id: string, w = 800, h = 1000) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&q=80`;

export const SITE_CONFIG = {
  name: "Kaosoff",
  tagline: "Peças artesanais autorais",
  email: "contato@kaosoff.com.br",
  whatsapp: "5511999999999",
  whatsappMessage: "Olá! Vim pelo site da Kaosoff e gostaria de saber mais.",
  instagram: "https://instagram.com/kaosoff",
  aboutText:
    "A Kaosoff é uma marca dedicada à criação de peças artesanais exclusivas, unindo criatividade, qualidade e atenção aos detalhes. Produzimos itens feitos à mão, como crochê, cerâmica e outras criações autorais, valorizando o trabalho artesanal e a autenticidade em cada peça.",
};

export const drops: Drop[] = [
  {
    id: "drop-1",
    slug: "inverno-urbano",
    name: "Inverno Urbano",
    description:
      "Uma coleção que une o artesanal ao urbano — balaclavas em crochê, cerâmicas escuras e peças que aquecem corpo e alma.",
    launchDate: "2026-06-15T12:00:00.000Z",
    coverImage: img("1558618666-fcd25c85cd64", 1200, 800),
    productIds: ["prod-1", "prod-2", "prod-3", "prod-4"],
    isActive: true,
  },
  {
    id: "drop-2",
    slug: "raizes",
    name: "Raízes",
    description:
      "Cerâmicas orgânicas, macramês suspensos e amigurumis que carregam histórias em cada ponto e cada argila.",
    launchDate: "2026-09-01T18:00:00.000Z",
    coverImage: img("1610701596007-d2b4aeba5243", 1200, 800),
    productIds: ["prod-5", "prod-6", "prod-7"],
    isActive: true,
  },
  {
    id: "drop-3",
    slug: "solsticio",
    name: "Solstício",
    description:
      "Chapéus de palha customizados, crochês leves e peças que celebram o calor e a luz do verão.",
    launchDate: "2025-12-21T12:00:00.000Z",
    coverImage: img("1523381210436-38389fa566ec", 1200, 800),
    productIds: ["prod-8", "prod-9"],
    isActive: false,
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    slug: "balaclava-noite",
    name: "Balaclava Noite",
    description:
      "Balaclava em crochê com fio de algodão premium, tingimento artesanal em preto profundo. Protege do frio sem abrir mão do estilo.",
    materials: "Algodão 100%, tingimento natural",
    dimensions: "Tamanho único — adaptável",
    price: 189,
    category: "balaclavas",
    images: [
      img("1558618666-fcd25c85cd64"),
      img("1582793829649-cc2b25d6b3e6"),
    ],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-1",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "prod-2",
    slug: "vaso-escuro",
    name: "Vaso Escuro",
    description:
      "Vaso de cerâmica com acabamento fosco e textura orgânica. Cada peça apresenta variações únicas de tonalidade.",
    materials: "Argila de alta temperatura, esmalte fosco",
    dimensions: "18cm altura × 12cm diâmetro",
    price: 245,
    category: "ceramica",
    images: [
      img("1610701596007-d2b4aeba5243"),
      img("1578746923794-7f5f977781b4"),
    ],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-1",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "prod-3",
    slug: "cachecol-trama",
    name: "Cachecol Trama",
    description:
      "Cachecol em crochê com ponto aberto e acabamento irregular — a imperfeição como assinatura.",
    materials: "Lã merino, fio de algodão",
    dimensions: "180cm comprimento × 25cm largura",
    price: 165,
    originalPrice: 198,
    category: "croche",
    images: [img("1582793829649-cc2b25d6b3e6")],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-1",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "prod-4",
    slug: "chapeu-palha-negro",
    name: "Chapéu Palha Negro",
    description:
      "Chapéu de palha tingido à mão em preto. Aba larga com detalhe em crochê na base.",
    materials: "Palha natural, fio de algodão",
    dimensions: "Aba 12cm, circunferência 58cm",
    price: 220,
    category: "chapeus",
    images: [img("1523381210436-38389fa566ec")],
    status: "sold",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-1",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "prod-5",
    slug: "suporte-macrame",
    name: "Suporte Macramê",
    description:
      "Suporte de parede em macramê para plantas, com nós artesanais e barbante de algodão cru.",
    materials: "Barbante de algodão cru",
    dimensions: "90cm comprimento total",
    price: 175,
    category: "macrame",
    images: [img("1485950222802-d2308b03d4b7")],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-2",
    availableAt: "2026-09-01T18:00:00.000Z",
    createdAt: "2026-09-01T18:00:00.000Z",
  },
  {
    id: "prod-6",
    slug: "amigurumi-corvo",
    name: "Amigurumi Corvo",
    description:
      "Corvo em amigurumi com olhos bordados à mão. Peça colecionável e afetiva.",
    materials: "Lã acrílica hipoalergênica, enchimento antialérgico",
    dimensions: "22cm altura",
    price: 145,
    category: "amigurumi",
    images: [img("1582793829649-cc2b25d6b3e6", 800, 800)],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-2",
    availableAt: "2026-09-01T18:00:00.000Z",
    createdAt: "2026-09-01T18:00:00.000Z",
  },
  {
    id: "prod-7",
    slug: "bowl-raiz",
    name: "Bowl Raiz",
    description:
      "Tigela de cerâmica com borda irregular e interior esmaltado em branco. Feita no torno, acabada à mão.",
    materials: "Argila vermelha, esmalte branco",
    dimensions: "14cm diâmetro × 6cm altura",
    price: 198,
    category: "ceramica",
    images: [img("1578746923794-7f5f977781b4")],
    status: "available",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-2",
    availableAt: "2026-09-01T18:00:00.000Z",
    createdAt: "2026-09-01T18:00:00.000Z",
  },
  {
    id: "prod-8",
    slug: "chapeu-solsticio",
    name: "Chapéu Solstício",
    description: "Chapéu de verão com faixa em crochê e detalhe em renda.",
    materials: "Palha, renda de algodão",
    dimensions: "Aba 10cm",
    price: 195,
    category: "chapeus",
    images: [img("1523381210436-38389fa566ec")],
    status: "sold",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-3",
    createdAt: "2025-12-21T12:00:00.000Z",
  },
  {
    id: "prod-9",
    slug: "amigurumi-sol",
    name: "Amigurumi Sol",
    description: "Sol em amigurumi com raios em crochê — peça decorativa.",
    materials: "Lã acrílica",
    dimensions: "18cm diâmetro",
    price: 128,
    category: "amigurumi",
    images: [img("1582793829649-cc2b25d6b3e6", 800, 800)],
    status: "sold",
    isUnique: true,
    isCustomOrder: false,
    dropId: "drop-3",
    createdAt: "2025-12-21T12:00:00.000Z",
  },
  {
    id: "prod-10",
    slug: "encomenda-personalizada",
    name: "Encomenda Personalizada",
    description:
      "Solicite uma peça feita sob medida — escolha categoria, materiais e referências. Cada encomenda é única e feita com dedicação.",
    materials: "A combinar",
    dimensions: "A combinar",
    price: 0,
    category: "croche",
    images: [img("1558618666-fcd25c85cd64")],
    status: "available",
    isUnique: true,
    isCustomOrder: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const customOrders: CustomOrder[] = [
  {
    id: "order-1",
    orderNumber: "KAO-2026-0042",
    customerCpf: "12345678901",
    customerName: "Maria Silva",
    customerEmail: "maria@email.com",
    customerPhone: "11988887777",
    description:
      "Balaclava em crochê na cor cinza chumbo, com detalhe em ponto aberto na testa.",
    category: "balaclavas",
    status: "in_production",
    createdAt: "2026-05-10T10:00:00.000Z",
    updatedAt: "2026-05-20T14:30:00.000Z",
  },
  {
    id: "order-2",
    orderNumber: "KAO-2026-0038",
    customerCpf: "98765432100",
    customerName: "João Santos",
    customerEmail: "joao@email.com",
    customerPhone: "11977776666",
    description: "Vaso de cerâmica em formato orgânico, esmalte branco fosco.",
    category: "ceramica",
    status: "shipped",
    createdAt: "2026-04-01T09:00:00.000Z",
    updatedAt: "2026-05-01T16:00:00.000Z",
  },
];

export const CATEGORIES: Category[] = [
  "ceramica",
  "croche",
  "macrame",
  "chapeus",
  "balaclavas",
  "amigurumi",
];
